dist: trusty

language: scala

services:
  - rabbitmq

sudo: false

jdk:
  - openjdk8

scala:
  - 2.12.15
  - 2.13.8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  - $HOME/.cache/coursier
